name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libtins
      run: sudo apt-get update && sudo apt-get install -y libtins-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
